name: GitHub Classroom Workflow

on: [push]

jobs:
  grade:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: andstor/file-existence-action@v2
        with:
          files: "instructions.md"
          fail: true
      - uses: actions/github-script@v6
        with:
          script: core.setOutput('Points', '10/10')
