name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  instructions-file:
    name: Check for instructions file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: andstor/file-existence-action@v2
        with:
          files: "instructions.md"
          fail: true
      - uses: actions/github-script@v6
        with:
          script: |
            core.notice('Points 10/10', {
              title: 'Instructions File',
            })
  readme-file:
    name: Check for readme file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: andstor/file-existence-action@v2
        with:
          files: "README.md"
          fail: true
      - uses: actions/github-script@v6
        with:
          script: |
            core.notice('Points 10/10', {
              title: 'README File',
            })
  autograding:
    if: ${{ always() }}
    needs:
      - instructions-file
      - readme-file
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
      - uses: actions/github-script@v6
        with:
          script: |
            core.summary
              .addHeading('Grading Results')
              .addTable([
                [{data: 'Test', header: true}, {data: 'Result', header: true}],
                ['Instructions File', ${{ needs.instructions-file.result == 'success' && 'Pass ✅' || 'Fail ❌' }}],
                ['README File', ${{ needs.readme-file.result == 'success' && 'Pass ✅' || 'Fail ❌' }}]
              ])
              .write()